version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=signup
      - MYSQL_ROOT_PASSWORD=1234567
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local

## if not connect db:
#  ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY '1234567';
#  flush privileges;
